name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Ensure this version is compatible with your package
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine  # Include twine in the installation
    - name: Build package
      run: python -m build  # Updated to use build system
    - name: Publish package
      run: twine upload dist/*  # Correct syntax for Twine upload
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
